import Head from 'next/head'
import { useRef } from 'react'  
import Image from 'next/image'
import { MicrophoneIcon,  ViewGridIcon } from '@heroicons/react/solid'
import { SearchIcon } from '@heroicons/react/outline'
import Avatar from '../components/Avatar'
import Footer from '../components/Footer'
import { useRouter, userRouter } from 'next/router'

export default function Home() {

  const searchInputRef = useRef(null);
  const router = useRouter();

  const Search = (e)=>{
    e.preventDefault();
    const term = searchInputRef.current.value;

    if(!term) return;

    router.push(`/search?term=${term}`)



  };

  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <Head>
        <title>Google Ruby</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <header className="flex w-full p-5 justify-between text-sm text-gray-700">
        {/* left */}

        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>

        {/* right */}
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>
          {/* Icon */}
          <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer"/>

          {/* Avatar */}
          <Avatar url="https://media-exp3.licdn.com/dms/image/C4D03AQGRwbLiW4XYwg/profile-displayphoto-shrink_200_200/0/1595402185572?e=1631145600&v=beta&t=H2r6svvYV-EG-jL8LtLL1sOLUmeCtX5SMvX5NB1pLfY"/>
        </div>
      </header>

      {/* Body */}
      <form className="flex flex-col items-center mt-40 flex-grow w-4/5">
        <Image src="https://cdn.pixabay.com/photo/2015/09/14/04/19/google-939112_960_720.png"
        width={300} height={100} alt="profile"/>
        <div className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg rounded-full 
          max-w-md border border-gray-200 px-5 
          py-3 items-center
          sm:max-w-xl lg:max-w-2xl">
          <SearchIcon className="h-5 mr-3 text-gray-500"/>
          <input ref={searchInputRef} type="text" className="focus:outline-none  flex-grow   border-gray-200 "/>
          <MicrophoneIcon className="h-5 animate-pulse" />
        </div>

        <div className="flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4">
          <button onClick={Search} className="btn">Google Search</button>
          <button onClick={Search} className="btn">I am Feeling Luck</button>
        </div>
        
      </form>

      {/* footer */}
      < Footer />
    </div>
  )};

